export const top_dashboard_data = [
    {
        id: 1,
        topBorder_color: "hsl(208, 92%, 53%)",
        platformURL: "../images/icon-facebook.svg",
        username: "@nathanf",
        count: 1987,
        metric: "Followers",
        changeIconUrl: "../public/images/icon-up.svg",
        change: 12,
        changeType: "up",
    },
    {
        id: 2,
        topBorder_color: "hsl(203, 89%, 53%)",
        platformURL: "../public/images/icon-twitter.svg",
        username: "@nathanf",
        count: 1044,
        metric: "Followers",
        changeIconUrl: "../public/images/icon-up.svg",
        change: 99,
        changeType: "up",
    },
    {
        id: 3,

        topBorder_color:
            "linear-gradient(to right,hsl(37, 97%, 70%),hsl(329, 70%, 58%))",
        platformURL: "../public/images/icon-instagram.svg",
        username: "@realnathanf",
        count: "11k",
        metric: "Followers",
        changeIconUrl: "../public/images/icon-up.svg",
        change: 1099,
        changeType: "up",
    },
    {
        id: 4,
        topBorder_color: "hsl(348, 97%, 39%)",
        platformURL: "../public/images/icon-youtube.svg",
        username: "Nathan F.",
        count: 8239,
        metric: "Subscribers",
        changeIconUrl: "../public/images/icon-down.svg",
        change: 144,
        changeType: "down",
    },
];

export const bottom_dashboard_data = [
    {
        id: 1,
        metric: "Page Views",
        platformURL: "../images/icon-facebook.svg",
        platformAlt: "Facebook icon",
        count: 87,
        changeIconUrl: "../public/images/icon-up.svg",
        change: 3,
        changeType: "up",
    },
    {
        id: 2,
        metric: "Likes",
        platformURL: "../images/icon-facebook.svg",
        platformAlt: "Facebook icon",
        count: 52,
        changeIconUrl: "../public/images/icon-down.svg",
        change: 2,
        changeType: "down",
    },
    {
        id: 3,
        platformURL: "../public/images/icon-instagram.svg",
        platformAlt: "Instagram icon",
        metric: "Likes",
        count: 5462,
        changeIconUrl: "../public/images/icon-up.svg",
        change: 2257,
        changeType: "up",
    },
    {
        id: 4,
        platformURL: "../public/images/icon-instagram.svg",
        platformAlt: "Instagram icon",
        metric: "Profile Views",
        count: "52k",
        changeIconUrl: "../public/images/icon-up.svg",
        change: 1375,
        changeType: "up",
    },
    {
        id: 5,
        platformURL: "../public/images/icon-twitter.svg",
        platformAlt: "Twitter icon",
        metric: "Retweets",
        count: 117,
        changeIconUrl: "../public/images/icon-up.svg",
        change: 303,
        changeType: "up",
    },
    {
        id: 6,
        platformURL: "../public/images/icon-twitter.svg",
        platformAlt: "Twitter icon",
        metric: "Likes",
        count: 507,
        changeIconUrl: "../public/images/icon-up.svg",
        change: 553,
        changeType: "up",
    },
    {
        id: 7,
        platformURL: "../public/images/icon-youtube.svg",
        platformAlt: "YouTube icon",
        metric: "Likes",
        count: 107,
        changeIconUrl: "../public/images/icon-up.svg",
        change: 19,
        changeType: "up",
    },
    {
        id: 8,
        platformURL: "../public/images/icon-youtube.svg",
        platformAlt: "YouTube icon",
        metric: "Total Views",
        count: 1407,
        changeIconUrl: "../public/images/icon-up.svg",
        change: 12,
        changeType: "up",
    },
];
